# circos.conf
karyotype = karyotype.txt

# This is the gene_density_plot for 
<plots>
<plot>
    type       = scatter
    file       = gene_density_100kb.bed
    r1         = 0.95r
    r0         = 0.50r
    color      = blues-8-seq
    min        = 0
    max        = 25
    orientation = out
</plot>

<plot>
    type       = heatmap
    file       = D_antillarum_repeat_content.bed
    r1         = 1.10r
    r0         = 1r
    orientation = out
    color = blues-8-seq
    scale_log_base = 1.0
    color_mapping = 1
</plot>

</plots>

################################################################
# The remaining content is standard and required. It is imported 
# from default files in the Circos distribution.
#
# These should be present in every Circos configuration file and
# overridden as required. To see the content of these files, 
# look in etc/ in the Circos distribution.

<image>
<<include etc/image.conf>>
</image>

# RGB/HSV color definitions, color lists, location of fonts, fill patterns.
# Included from Circos distribution.
<<include etc/colors_fonts_patterns.conf>>

# Debugging, I/O and other system parameters
# Included from Circos distribution.
<<include etc/housekeeping.conf>>

<<include /home/apodomenia/Nick/2024-11-03_Discradica_antillarum/Discradisca_antillarum/circos_visualization/ideogram.conf>>

<colors>
nf = 1,0,0,0
blue_vlight = 204,229,255,0.1
blue_light = 102,178,255,0.1
green_vlight = 204,255,204,0.1
green_light = 47,186,12,0.1
orange_orange = 164,98,0,0.1
orange_light = 250,205,57,0.1
orange_vlight = 255,232,157,0.1
orange_vvlight = 255,245,210,0.1
</colors>
